name: Java Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: |
          if ! mvn --batch-mode --update-snapshots test; then
            echo "Tests failed! Check the logs above for details."
            exit 1
          fi
        continue-on-error: false